# Generated by Django 5.1.7 on 2025-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fields",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("selections", models.JSONField(default=list)),
            ],
        ),
    ]
